INSERT INTO public.currencies ("label", value) VALUES('EUR - Euro', 'EUR');
INSERT INTO public.currencies ("label", value) VALUES('JPY - Japanese Yen', 'JPY');
INSERT INTO public.currencies ("label", value) VALUES('BGN - Bulgarian Lev', 'BGN');
INSERT INTO public.currencies ("label", value) VALUES('USD - United States Dollar', 'USD');  
INSERT INTO public.currencies ("label", value) VALUES('CZK - Czech Koruna', 'CZK');
INSERT INTO public.currencies ("label", value) VALUES('DKK - Danish Krone', 'DKK');
INSERT INTO public.currencies ("label", value) VALUES('GBP - British Pound Sterling', 'GBP');
INSERT INTO public.currencies ("label", value) VALUES('HUF - Hungarian Forint', 'HUF');      
INSERT INTO public.currencies ("label", value) VALUES('PLN - Polish Zloty', 'PLN');
INSERT INTO public.currencies ("label", value) VALUES('RON - Romanian Leu', 'RON');
INSERT INTO public.currencies ("label", value) VALUES('SEK - Swedish Krona', 'SEK');
INSERT INTO public.currencies ("label", value) VALUES('CHF - Swiss Franc', 'CHF');
INSERT INTO public.currencies ("label", value) VALUES('ISK - Icelandic Króna', 'ISK');       
INSERT INTO public.currencies ("label", value) VALUES('NOK - Norwegian Krone', 'NOK');       
INSERT INTO public.currencies ("label", value) VALUES('HRK - Croatian Kuna', 'HRK');
INSERT INTO public.currencies ("label", value) VALUES('RUB - Russian Ruble', 'RUB');
INSERT INTO public.currencies ("label", value) VALUES('TRY - Turkish Lira', 'TRY');
INSERT INTO public.currencies ("label", value) VALUES('AUD - Australian Dollar', 'AUD');
INSERT INTO public.currencies ("label", value) VALUES('BRL - Brazilian Real', 'BRL');
INSERT INTO public.currencies ("label", value) VALUES('CAD - Canadian Dollar', 'CAD');
INSERT INTO public.currencies ("label", value) VALUES('CNY - Chinese Yuan Renminbi', 'CNY');
INSERT INTO public.currencies ("label", value) VALUES('HKD - Hong Kong Dollar', 'HKD');
INSERT INTO public.currencies ("label", value) VALUES('IDR - Indonesian Rupiah', 'IDR');
INSERT INTO public.currencies ("label", value) VALUES('ILS - Israeli New Sheqel', 'ILS');
INSERT INTO public.currencies ("label", value) VALUES('INR - Indian Rupee', 'INR');
INSERT INTO public.currencies ("label", value) VALUES('KRW - South Korean Won', 'KRW');
INSERT INTO public.currencies ("label", value) VALUES('MXN - Mexican Peso', 'MXN');
INSERT INTO public.currencies ("label", value) VALUES('MYR - Malaysian Ringgit', 'MYR');
INSERT INTO public.currencies ("label", value) VALUES('NZD - New Zealand Dollar', 'NZD');
INSERT INTO public.currencies ("label", value) VALUES('PHP - Philippine Peso', 'PHP');
INSERT INTO public.currencies ("label", value) VALUES('SGD - Singapore Dollar', 'SGD');
INSERT INTO public.currencies ("label", value) VALUES('THB - Thai Baht', 'THB');
INSERT INTO public.currencies ("label", value) VALUES('ZAR - South African Rand', 'ZAR');